# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/austin/Desktop/projects/zybo/zybo_img_proc/vhdl/Zybo-Z7-Master.xdc

# Block Designs: bd/img_proc/img_proc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc || ORIG_REF_NAME==img_proc} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_processing_system7_0_0/img_proc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_processing_system7_0_0 || ORIG_REF_NAME==img_proc_processing_system7_0_0} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_xbar_2/img_proc_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_xbar_2 || ORIG_REF_NAME==img_proc_xbar_2} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_axi_interconnect_0_1/img_proc_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_axi_interconnect_0_1 || ORIG_REF_NAME==img_proc_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_proc_sys_reset_0_0/img_proc_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_proc_sys_reset_0_0 || ORIG_REF_NAME==img_proc_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_xbar_3/img_proc_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_xbar_3 || ORIG_REF_NAME==img_proc_xbar_3} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_axi_interconnect_1_0/img_proc_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_axi_interconnect_1_0 || ORIG_REF_NAME==img_proc_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_axi_vdma_0_0/img_proc_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_axi_vdma_0_0 || ORIG_REF_NAME==img_proc_axi_vdma_0_0} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_v_vid_in_axi4s_0_0/img_proc_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==img_proc_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_axis_subset_converter_0_0/img_proc_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_axis_subset_converter_0_0 || ORIG_REF_NAME==img_proc_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_xlconstant_0_1/img_proc_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_xlconstant_0_1 || ORIG_REF_NAME==img_proc_xlconstant_0_1} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_axi_gpio_0_1/img_proc_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_axi_gpio_0_1 || ORIG_REF_NAME==img_proc_axi_gpio_0_1} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_ila_0_1/img_proc_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_ila_0_1 || ORIG_REF_NAME==img_proc_ila_0_1} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_video_stream_mux_0_0/img_proc_video_stream_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_video_stream_mux_0_0 || ORIG_REF_NAME==img_proc_video_stream_mux_0_0} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_v_tpg_0_0/img_proc_v_tpg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_v_tpg_0_0 || ORIG_REF_NAME==img_proc_v_tpg_0_0} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_dvi2rgb_0_1/img_proc_dvi2rgb_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_dvi2rgb_0_1 || ORIG_REF_NAME==img_proc_dvi2rgb_0_1} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_auto_pc_0/img_proc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_auto_pc_0 || ORIG_REF_NAME==img_proc_auto_pc_0} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_auto_pc_1/img_proc_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_auto_pc_1 || ORIG_REF_NAME==img_proc_auto_pc_1} -quiet] -quiet

# XDC: bd/img_proc/img_proc_ooc.xdc
