# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/austin/Desktop/projects/zybo/zybo_img_proc/vhdl/Zybo-Z7-Master.xdc

# Block Designs: bd/img_proc/img_proc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc || ORIG_REF_NAME==img_proc} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_dvi2rgb_0_0/img_proc_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_dvi2rgb_0_0 || ORIG_REF_NAME==img_proc_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_rgb2dvi_0_0/img_proc_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_rgb2dvi_0_0 || ORIG_REF_NAME==img_proc_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_clk_wiz_0_0/img_proc_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_clk_wiz_0_0 || ORIG_REF_NAME==img_proc_clk_wiz_0_0} -quiet] -quiet

# IP: bd/img_proc/ip/img_proc_xlconstant_0_0/img_proc_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_xlconstant_0_0 || ORIG_REF_NAME==img_proc_xlconstant_0_0} -quiet] -quiet

# XDC: bd/img_proc/img_proc_ooc.xdc
