# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/austin/Desktop/projects/zybo/zybo_img_proc/vhdl/Zybo-Z7-Master.xdc

# Block Designs: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/img_proc_baseline.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_baseline || ORIG_REF_NAME==img_proc_baseline} -quiet] -quiet

# IP: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/ip/img_proc_baseline_dvi2rgb_0_1/img_proc_baseline_dvi2rgb_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_baseline_dvi2rgb_0_1 || ORIG_REF_NAME==img_proc_baseline_dvi2rgb_0_1} -quiet] -quiet

# IP: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/ip/img_proc_baseline_rgb2dvi_0_0/img_proc_baseline_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_baseline_rgb2dvi_0_0 || ORIG_REF_NAME==img_proc_baseline_rgb2dvi_0_0} -quiet] -quiet

# IP: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/ip/img_proc_baseline_clk_wiz_0_0/img_proc_baseline_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_baseline_clk_wiz_0_0 || ORIG_REF_NAME==img_proc_baseline_clk_wiz_0_0} -quiet] -quiet

# IP: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/ip/img_proc_baseline_xlconstant_0_0/img_proc_baseline_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==img_proc_baseline_xlconstant_0_0 || ORIG_REF_NAME==img_proc_baseline_xlconstant_0_0} -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/img_proc_baseline_ooc.xdc
