# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_rgb2dvi_0_1/img_proc_test_rgb2dvi_0_1.xci
# IP: The module: 'img_proc_test_rgb2dvi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_rgb2dvi_0_1/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_test_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_rgb2dvi_0_1/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_test_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_rgb2dvi_0_1/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_test_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_rgb2dvi_0_1/img_proc_test_rgb2dvi_0_1.xci
# IP: The module: 'img_proc_test_rgb2dvi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_rgb2dvi_0_1/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_test_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_rgb2dvi_0_1/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_test_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_rgb2dvi_0_1/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_test_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
