# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/img_proc_test_dvi2rgb_0_1.xci
# IP: The module: 'img_proc_test_dvi2rgb_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_refclk/ila_refclk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_refclk || ORIG_REF_NAME==ila_refclk} -quiet] -quiet

# IP: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_pixclk/ila_pixclk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_pixclk || ORIG_REF_NAME==ila_pixclk} -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_refclk/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_refclk || ORIG_REF_NAME==ila_refclk} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_refclk/ila_refclk_ooc.xdc

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_timing_workaround.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_test_dvi2rgb_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/dvi2rgb.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_test_dvi2rgb_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/dvi2rgb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_test_dvi2rgb_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_pixclk/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_pixclk || ORIG_REF_NAME==ila_pixclk} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_pixclk/ila_pixclk_ooc.xdc

# IP: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/img_proc_test_dvi2rgb_0_1.xci
# IP: The module: 'img_proc_test_dvi2rgb_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_refclk/ila_refclk.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_refclk || ORIG_REF_NAME==ila_refclk} -quiet] -quiet

# IP: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_pixclk/ila_pixclk.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_pixclk || ORIG_REF_NAME==ila_pixclk} -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_refclk/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_refclk || ORIG_REF_NAME==ila_refclk} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_refclk/ila_refclk_ooc.xdc

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_timing_workaround.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_test_dvi2rgb_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/dvi2rgb.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_test_dvi2rgb_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/dvi2rgb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_test_dvi2rgb_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_pixclk/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_pixclk || ORIG_REF_NAME==ila_pixclk} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/img_proc/vivado/img_proc/img_proc.srcs/sources_1/bd/img_proc_test/ip/img_proc_test_dvi2rgb_0_1/src/ila_pixclk/ila_pixclk_ooc.xdc
