# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/ip/img_proc_baseline_rgb2dvi_0_0/img_proc_baseline_rgb2dvi_0_0.xci
# IP: The module: 'img_proc_baseline_rgb2dvi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/ip/img_proc_baseline_rgb2dvi_0_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_baseline_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/ip/img_proc_baseline_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_baseline_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/ip/img_proc_baseline_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_baseline_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/ip/img_proc_baseline_rgb2dvi_0_0/img_proc_baseline_rgb2dvi_0_0.xci
# IP: The module: 'img_proc_baseline_rgb2dvi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/ip/img_proc_baseline_rgb2dvi_0_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_baseline_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/ip/img_proc_baseline_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_baseline_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/austin/Desktop/projects/zybo/zybo_img_proc_baseline/vivado/img_proc_baseline/img_proc_baseline.srcs/sources_1/bd/img_proc_baseline/ip/img_proc_baseline_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_proc_baseline_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
